remark: a
home: /media/ags/DATA/CODE/vista/
#home: /home/eee/ug/15084015/aptos/
fold: 0
total_folds: 5
size: 224
top_lr: 1e-3
class_weights: None
cw_sampling: False
he_sampling: False
hard_ex_weight: 2
hard_df: weights/118_efficientnet-b5_f1_postraug2/diff.csv
num_samples: None
model_name: se_resnext101_32x4d
ext_text: test
mean: (0.485, 0.456, 0.406)
std: (0.229, 0.224, 0.225)
df_path: data/train.csv
sample_submission: data/sample.csv
data_folder: data/train_final/

phases: ["train", "val"]
batch_size:
    train: 8
    val: 8
    test: 8

num_workers: 12
num_classes: 14
ep2unfreeze: 2
num_epochs: 40
base_lr: None
momentum: 0.95
patience: 3
